repos:
- repo: local
    hooks:
    - id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        types: [python]
- repo : local
    hooks:
    - id: black
        name: black
        entry: poetry run black --check --diff --quiet --skip-magic-trailing-comma .
        language: system
        types: [python]